### ISSUE TITLE
No error if bathymetry file not read

### ISSUE THREAD

**Issue by davidbenncsiro** [CyprienBosserelle/xbeach_gpu#32]
If the bathymetry file is not read, the only indication in XBG_log.txt is that "Reading dep file" is missing.

For example, if the bathymetry file has a ".txt" file suffix, we see:
~~~
#################################
XBeach_GPU v0.0
#################################
model started at 20-09-2021 16:12:51
bathy: bathy-new.txt
bathy extension: txt
nx=624 ny=240 dx=10.000000 grdalpha=0.000000
~~~
whereas if the same file is given a ".dep" suffix, we have:
~~~
#################################
XBeach_GPU v0.0
#################################
model started at 28-09-2021 13:10:13
bathy: bathy-new.dep
bathy extension: dep
Reading dep file
For this type of bathy file please specify nx, ny, dx and grdalpha in the XBG_param.txt
nx=624 ny=240 dx=10.000000 grdalpha=0.000000
~~~
See https://github.com/CyprienBosserelle/xbeach_gpu/blob/master/Wave_gpu.cu#L1764

In the block of code pointed to above, either any file suffix could be assumed to be .dep or .bot or an error message could be output and the application could exit.

**Comment by davidbenncsiro** [comment]
@CyprienBosserelle this zip file contains the unmodified bathymetry file with no change to cols and rows and the modified file. The modified file has a .dep rather than .txt suffix.
[bathy.zip](https://github.com/CyprienBosserelle/xbeach_gpu/files/7248147/bathy.zip)

**Comment by CyprienBosserelle** [comment]
@davidbenncsiro, 
I fixed most of your problems on branch AddUEUmean 730f747.
 you can now call the bathy file `*.txt` as if it is a `*.dep`. Your crash was that the bathy was positive up whereas XBGPU takes positive down bathymetry. I added a new parameter that allow you to switch to posdown within XBGPU so you don't have to redo the file.
in you case I used: 
```
depfile   = ./bathy/bathy-new.dep;
posdown    = 0;
```

and the model worked...
![image](https://user-images.githubusercontent.com/3713631/135366912-f2f03f2c-a90a-4d08-aaf2-c930665fec0a.png)
